### ISSUE TITLE
Better/More Verbose Error Output

### ISSUE THREAD

**Issue by schuylermartin45** [anaconda-distribution/anaconda-linter#216]
Right now, I have to go into the linter code to get a definition/comments for the errors I am seeing.

It'd be nice to have a `--verbose` flag to dump more information about what the error means. Or maybe a query flag to get details about the error code?

Alternatively, we could host a Doxygen-style page that makes it easier to find the documentation in-code.

**Comment by marcoesters** [comment]
There is a `--verbose` flag already that outputs the long version of the errors. If there are errors that need a better explanation, I would suggest to update the docstrings (which are currently used to double as message templates).

There is an issue to improve the messaging system to not rely on doc strings, but that's a bigger rewrite: https://github.com/anaconda-distribution/anaconda-linter/issues/48

I'm closing this since the original ask for a `--verbose` flag already exists.

**Comment by schuylermartin45** [comment]
I guess I just never ran `-h` on the linter and completely missed this.

I feel like `-v` might be important enough, especially to new users, that it should be mentioned in the README? Or, at the very least, `-h` should be mentioned briefly.

**Comment by schuylermartin45** [comment]
Hopefully this will catch similar confusions in the future: https://github.com/anaconda-distribution/anaconda-linter/pull/219
