### ISSUE TITLE
Create unit tests for recipe checks

### ISSUE THREAD

**Issue by ous8292** [anaconda-distribution/anaconda-linter#49]
We need to create unit tests in order to check the recipe

**Comment by razzlestorm** [comment]
This PR [here](https://github.com/anaconda-distribution/anaconda-linter/pull/93/) lets us individually check recipes with custom input.

**Comment by razzlestorm** [comment]
Seems like the way forward is to: 
Abstract as much function logic away as possible, so that a unit test simply looks like:
```
def unit_test_name(params):
   var: data to test for this individual test
   assert statement
```
We'll investigate whether this is best done via a string, dictionary, or possibly setting a new Recipe object's `meta` attribute directly.

@marcoesters, just adding this here to track results from the meeting.
