### ISSUE TITLE
Create a simplified/compact display mode for linter errors

### ISSUE THREAD

**Issue by razzlestorm** [anaconda-distribution/anaconda-linter#79]
From @skupr-anaconda:
Can we simplify the linter output (for non verbose mode) to be like this one:
The following problems have been found:
```
<PACKAGE_NAME> <PACKAGE_VERSION>:
- Missing wheel package in requirements
- Missing setuptools package in requirements
- No license family specified
```
i.e., without words WARNING, ERROR, without line numbers, type of missing data.
It will be much more readable.

**Comment by ous8292** [comment]
Hey @razzlestorm @skupr-anaconda,

Just for clarification, do we want the default output to be the compact output or are we wanting a `--compact` flag with compact output.

It seems like the default output is pretty compact already, and we could trim the information there.

**Comment by marcoesters** [comment]
I think the default should stay the way it is and that we should add a `--compact` flag for the requested output.

I would not want to just trim the current default output. It has important information like line numbers that I would prefer to keep in the default output.

**Comment by ous8292** [comment]
Okay sounds good!

**Comment by danpetry** [comment]
On a related note, how about shortening the paths for default output to relative rather than full paths?

**Comment by ous8292** [comment]
I'm not sure how committed we are with the idea of a `-c` flag and `-v` flag, but we could also use a `-v` (verbose) and a '-vv` (very verbose) flag instead.

For example: 
- The compact output I've created could become the new default output.
- The current default would be `-v`, and become verbose, since it shows a nice amount of information
- The current verbose output would be `-vv` very verbose since it shows the most amount of information. 

I noticed that `lspci` uses this functionality. 
https://man7.org/linux/man-pages/man8/lspci.8.html

This way if someone uses both `-v` and `-vv` flag, it would default to the most verbose amount of information

Let me know what you guys think! Otherwise I can look more into other methods.

**Comment by danpetry** [comment]
> I think the default should stay the way it is and that we should add a --compact flag for the requested output.
> 
> I would not want to just trim the current default output. It has important information like line numbers that I would prefer to keep in the default output.

I agree with marco

**Comment by marcoesters** [comment]
I am not against the `-v*` concept. However, I have concerns about removing the "ERROR"/"WARNING"/"INFO" labels from the default output, especially since some output are not fixable (like the `check_gui` function). I would like to keep the severity levels in the default message so that parsers or inexperienced users can handle these properly.

**Comment by cjmartian** [comment]
Hello Friends,

I've been lurking about. After some thought on this issue, would it make sense to also have these flags change the logging level during runtime?

From my perspective, having shorter or longer output for the status of a given recipe accompanied by various logging messages could be helpful for users.

Cheers 🍻

**Comment by razzlestorm** [comment]
Can you expand a bit on what you mean by changing logging level during runtime? Like if someone chooses --compact, it only shows ERRORs, but if they choose `very-verbose`, it shows INFO and above?

**Comment by cjmartian** [comment]
> Can you expand a bit on what you mean by changing logging level during runtime? Like if someone chooses --compact, it only shows ERRORs, but if they choose `very-verbose`, it shows INFO and above?

Yeah exactly. It could possibly make it easier to debug later on if there were logging statements placed about the code that could be turned on easily by simply passing a flag. 

The issue I see there though is people wanting more precise linting output and then being bombarded by some debug logging.

**Comment by marcoesters** [comment]
We already have a way to set the minimum severity level to output with the `--severity` flag, which is more explicit than verbosity flags.

**Comment by schuylermartin45** [comment]
I believe this is captured in: https://github.com/anaconda-distribution/anaconda-linter/issues/227
Closing.
